const products = [
  {
    name: "Espada Justiceira Thundercats Lion Tamanho Real em Aço",
    price: 1424.0,
    imagePath: "/Captura de tela 2024-08-07 171904.png",
    discount: 0.1,
    sale: 12,
    releaseDate: new Date(),
    description: "Espada Justiceira Thundercats Lion Tamanho Real em Aço",
    stock: 13,
    category: "Espadas",
  },
  {
    name: "Machados de matar deuses de Valhalla",
    price: 990.0,
    imagePath: "machados.jpg",
    discount: 0.15,
    sale: 89,
    releaseDate: new Date(),
    description: "Machados duplos",
    stock: 25,
    category: "Machados",
  },
  {
    name: "Espada romana",
    price: 3500.0,
    imagePath: "espadaromana.jpg",
    discount: 0.4,
    sale: 7,
    releaseDate: new Date(),
    description: "A famosa espada romana",
    stock: 14,
    category: "Espadas",
  },
  {
    name: "Espada Katana Dragão Vermelho",
    price: 398.9,
    imagePath: "/Captura de tela 2024-08-07 172247.png",
    discount: 0.2,
    sale: 67,
    releaseDate: new Date(),
    description: "Espada japonesa",
    stock: 34,
    category: "Espadas",
  },
  {
    name: "Espadinha fura cavaleiro",
    price: 567.98,
    imagePath: "/184523054a495584a17.webp",
    discount: 0.1,
    sale: 56,
    releaseDate: new Date(),
    description: "Espada para furar cavaleiros",
    stock: 12,
    category: "Espadas",
  },
  {
    name: "Espaga grega",
    price: 2932.87,
    imagePath: "/espada.jpg",
    discount: 0.3,
    sale: 6,
    releaseDate: new Date(),
    description: "Espada da antiga Grecia",
    stock: 11,
    category: "Espadas",
  },
  {
    name: "Martelo do thor para comer peão",
    price: 10000.0,
    imagePath: "/Martelo do thor.jpg",
    discount: 0.2,
    sale: 200,
    releaseDate: new Date(),
    description: "Martelo do Deus Thor",
    stock: 45,
    category: "Martelos",
  },
  {
    name: "Escudo viking",
    price: 400.0,
    imagePath: "/Escudo viking.jpg",
    discount: 0.25,
    sale: 50,
    releaseDate: new Date(),
    description: "Escudo viking de madeira",
    stock: 13,
    category: "Escudos",
  },
  {
    name: "Elmo espartano",
    price: 690.0,
    imagePath: "/capacete espartano.jpg",
    discount: 0.17,
    sale: 67,
    releaseDate: new Date(),
    description: "Capacete de um guerreiro espartano",
    stock: 34,
    category: "Elmos",
  },
  {
    name: "Armadura samurai",
    price: 6488.0,
    imagePath: "/samurai.jpg",
    discount: 0.2,
    sale: 85,
    releaseDate: new Date(),
    description: "Armadura de um soldado samurai",
    stock: 43,
    category: "Armaduras",
  },
  {
    name: "Armadura medieval",
    price: 549.0,
    imagePath: "/Armadura medieval.jpg",
    discount: 0.35,
    sale: 115,
    releaseDate: new Date(),
    description: "armadura de metal de um guerreiro media",
    stock: 28,
    category: "Armaduras",
  },
  {
    name: "Armadura viking",
    price: 1263.0,
    imagePath: "/armadura viking.jpg",
    discount: 0.22,
    sale: 32,
    releaseDate: new Date(),
    description: "Armadura de um guerreiro viking",
    stock: 77,
    category: "Armaduras",
  },
  {
    name: "Barco viking",
    price: 14990.0,
    imagePath: "/barco viking.jpg",
    discount: 0.05,
    sale: 12,
    releaseDate: new Date(),
    description: "Uma embarcação viking em tamanho real",
    stock: 3,
    category: "Embarcação",
  },
  {
    name: "Punhal Medieval",
    price: 1499.0,
    imagePath: "/punhal-medieval.jpg",
    discount: 0.15,
    sale: 94,
    releaseDate: new Date(),
    description: "Um punhal medieval detalhado",
    stock: 27,
    category: "Punhais",
  },
  {
    name: "Espada Asteca",
    price: 2700.0,
    imagePath: "/espada-asteca.jpg",
    discount: 0.1,
    sale: 7,
    releaseDate: new Date(),
    description: "Espada feita de metais astecas",
    stock: 8,
    category: "Espadas",
  },
  {
    name: "Carruagem Viking",
    price: 4900.0,
    imagePath: "/carruagem.jpg",
    discount: 0.1,
    sale: 3,
    releaseDate: new Date(),
    description: "Carruagem Viking",
    stock: 2,
    category: "Carruagem",
  },
  {
    name: "Elmo Romano",
    price: 3200.0,
    imagePath: "/capacete-romano.jpg",
    discount: 0.1,
    sale: 87,
    releaseDate: new Date(),
    description: "Elmo usado por soldados romanos",
    stock: 21,
    category: "Elmos",
  },
  {
    name: "Elmo Inca",
    price: 2400.0,
    imagePath: "/capacete-inca.jpg",
    discount: 0.14,
    sale: 13,
    releaseDate: new Date(),
    description: "Elmo Inca",
    stock: 8,
    category: "Elmos",
  },
  {
    name: "Elmo Viking",
    price: 1500.0,
    imagePath: "/elmo-viking.jpg",
    discount: 0.09,
    sale: 67,
    releaseDate: new Date(),
    description: "Elmo Viking com chifres",
    stock: 18,
    category: "Elmos",
  },
];
for (const product of products) {
  db.produtos.insertOne(product);
}
